New version of ldap provisioner
rciam/comanage-registry pull request #103
Opened 2021-06-29 11:46 UTC by lionick

ALTER TABLE cm_co_ldap_provisioner_targets ADD COLUMN attr_opts boolean;
ALTER TABLE cm_co_ldap_provisioner_targets ADD COLUMN hierarchy_format boolean;
ALTER TABLE cm_co_ldap_provisioner_targets  ADD COLUMN oc_voperson boolean;
ALTER TABLE cm_co_ldap_provisioner_targets  DROP COLUMN opt_lang;
ALTER TABLE cm_co_ldap_provisioner_targets  DROP COLUMN opt_role;

2021-06-30 07:39 UTC, NicolasLiampotis requested changes
Please add changes to CHANGELOG under `## [Unreleased]`

2021-06-30 10:06 UTC, lionick commented
> Please add changes to CHANGELOG under `## [Unreleased]`

Done.

2021-07-08 06:58 UTC, ioigoume requested changes

2021-07-08 06:58 UTC, ioigoume commented on app/Plugin/LdapProvisioner/Model/CoLdapProvisionerDn.php
> +    if($coGroupData['CoGroup']['cou_id'] != NULL && $coProvisioningTargetData['CoLdapProvisionerTarget']['hierarchy_format']) {
perhaps use this: !is_null($coGroupData['CoGroup']['cou_id'])

2021-07-08 06:58 UTC, ioigoume commented on app/Plugin/LdapProvisioner/View/CoLdapProvisionerTargets/fields.inc
> +            print '<div id="oc_' . $oc . '_div" class="nested">';
class nested is missing from co-base.css? Have you tested how ui will behave if you import that rule?

2021-07-09 10:07 UTC, merged