CO_Person_Role_country_attribute
rciam/comanage-registry pull request #104
Opened 2021-07-02 11:12 UTC by ioigoume

Add Country ISO codes.
Allow country field as the only address input during registration.

2021-07-06 08:52 UTC, lionick requested changes

2021-07-06 08:52 UTC, lionick commented on app/Lib/lang.php
> +    "AX" => "Ã…land Islands",
Is this the correct name?

2021-07-06 08:52 UTC, lionick commented on app/Lib/lang.php
> +    "CI" => "CÃ´te d'Ivoire",
Is this the correct name?

2021-07-06 14:42 UTC, ioigoume commented on app/Lib/lang.php
> +    "CI" => "CÃ´te d'Ivoire",
Done

2021-07-12 09:28 UTC, lionick approved these changes
LGTM

2021-07-12 09:34 UTC, NicolasLiampotis approved these changes
LGTM

2021-07-12 09:34 UTC, merged