Handle pending petitions
rciam/comanage-registry pull request #114
Opened 2021-08-04 12:34 UTC by lionick

2021-09-15 09:54 UTC, ioigoume requested changes

2021-09-15 09:54 UTC, ioigoume commented on app/Controller/CoPetitionsController.php
> +                'op' => 'resume'
`resume` have to be an enumerator variable

2021-09-15 09:54 UTC, ioigoume commented on app/Controller/CoPetitionsController.php
> +    if(!empty($this->params['named']['op']) && $this->params['named']['op'] == 'resume') {
`resume` : enumerator

2021-09-16 07:59 UTC, ioigoume approved these changes
LGTM

2021-09-22 11:02 UTC, NicolasLiampotis approved these changes
LGTM

2021-09-22 11:02 UTC, merged