Record_authentication_events_via_proxy
rciam/comanage-registry pull request #124
Opened 2021-09-27 17:44 UTC by ioigoume

- Enable AuthenticationEvents index,view,add through REST API.Support "
- Proxy login" authentication event type.

2021-09-27 22:39 UTC, NicolasLiampotis requested changes
Change "Proxy Login" to "User Login" (or "User Authentication")

2021-09-27 22:39 UTC, NicolasLiampotis commented on app/Lib/enum.php
> +  const ProxyLogin             = 'PI';
ProxyLogin -> UserLogin = 'UL'

2021-09-27 22:39 UTC, NicolasLiampotis commented on app/Lib/lang.php
> +    AuthenticationEventEnum::ProxyLogin    => 'Proxy Login'
ProxyLogin --> UserLogin

2021-09-27 22:39 UTC, NicolasLiampotis commented on CHANGELOG.md
> +- Support "Proxy login" authentication event type.
"Proxy Login" --> "User Login"

2021-09-27 22:39 UTC, NicolasLiampotis commented on app/Model/AuthenticationEvent.php
> +                            AuthenticationEventEnum::ProxyLogin,
ProxyLogin --> UserLogin

2021-09-28 07:32 UTC, ioigoume commented on app/Lib/enum.php
> +  const ProxyLogin             = 'PI';
Done

2021-09-28 07:38 UTC, ioigoume commented on app/Model/AuthenticationEvent.php
> +                            AuthenticationEventEnum::ProxyLogin,
Done

2021-09-28 07:38 UTC, ioigoume commented on app/Lib/lang.php
> +    AuthenticationEventEnum::ProxyLogin    => 'Proxy Login'
Done

2021-09-28 07:38 UTC, ioigoume commented on CHANGELOG.md
> +- Support "Proxy login" authentication event type.
Done

2021-09-28 08:25 UTC, NicolasLiampotis approved these changes
LGTM

2021-09-28 08:25 UTC, merged