Add IdP Source in CO Person's profile(canvas web page) in Organizational Identities table
rciam/comanage-registry pull request #14
Opened 2019-05-31 09:59 UTC by ioigoume

This fix enables the extraction of the AthenticationAuthority assertion attribute from the IdP's metadata. Then we store the url by inserting the value into the OrgIdentity table, and finally we depict in the CO Person's profile.

We need to add auth_idp_url column in org_identities table
`alter table cm_org_identities add column auth_idp_url varchar(128);`

We need to request from shibboleth SP linked with COManage to fetch the data we need. The configuration should be updated by adding 
```

// LEAVE ALL THE OTHER AttributeExtractor entries as is and add the following line
<AttributeExtractor type="Assertion" AuthenticatingAuthority="AuthenticatingAuthority"/>
```

As far as the old users are concerned, the source field will be updated automatically as soon as they use an IdP to log into COManage.

2019-05-31 13:48 UTC, NicolasLiampotis requested changes

2019-05-31 13:48 UTC, NicolasLiampotis commented on CHANGELOG.md
> +- Retrieve AuthenticatingAuthority and depict in CO Person's canvas/profile
Move to Added section (features)

2019-05-31 13:48 UTC, NicolasLiampotis commented on app/Config/Schema/schema.xml
> +    <field name="auth_idp_url" type="C" size="128" />
Rename to authn_authority

2019-05-31 13:48 UTC, NicolasLiampotis commented on app/Lib/lang.php
> +  'fd.auth_idp_url' => 'Authenticating IdP',
Same as above

2019-05-31 13:48 UTC, NicolasLiampotis commented on app/Model/OrgIdentity.php
> +    'auth_idp_url' => array(
Same as above

2019-05-31 13:48 UTC, NicolasLiampotis commented on app/Model/OrgIdentity.php
> +    $authIdPUrl = isset($_SERVER['AuthenticatingAuthority']) ? $_SERVER['AuthenticatingAuthority'] : "";
Same as above

2019-05-31 13:48 UTC, NicolasLiampotis commented on app/Model/OrgIdentity.php
> +    $authIdPUrl = isset($_SERVER['AuthenticatingAuthority']) ? $_SERVER['AuthenticatingAuthority'] : "";
Same as above

2019-05-31 13:48 UTC, NicolasLiampotis commented on app/View/OrgIdentities/fields.inc
> +                  print filter_var($org_identities[0]['OrgIdentity']['auth_idp_url'],FILTER_SANITIZE_SPECIAL_CHARS);
Same as above

2019-05-31 13:48 UTC, NicolasLiampotis commented on app/Model/OrgIdentity.php
> +    $authIdPUrl = isset($_SERVER['AuthenticatingAuthority']) ? $_SERVER['AuthenticatingAuthority'] : "";
Change "" to null if things don't break

2019-05-31 13:48 UTC, NicolasLiampotis commented on app/View/OrgIdentities/fields.inc
> +                if(!empty($org_identities[0]['OrgIdentity']['auth_idp_url'])) {
Same as above

2019-05-31 13:48 UTC, NicolasLiampotis commented on app/View/OrgIdentities/fields.inc
> +                  print filter_var($org_identities[0]['OrgIdentity']['auth_idp_url'],FILTER_SANITIZE_SPECIAL_CHARS);
Same as above

2019-05-31 13:48 UTC, NicolasLiampotis commented on app/View/CoPeople/fields.inc
> +                            print "( <span style='font-weight: bold;'>IdP :</span> " .filter_var($link['OrgIdentity']['auth_idp_url'] ,FILTER_SANITIZE_SPECIAL_CHARS). ") <br>";
Remove IdP label

2019-05-31 13:48 UTC, NicolasLiampotis commented on app/View/OrgIdentities/fields.inc
> +              <?php print("Authenticating Authority(IdP)"); ?>
Add space - it's free :-)

2019-05-31 13:56 UTC, ioigoume commented on app/View/OrgIdentities/fields.inc
> +                if(!empty($org_identities[0]['OrgIdentity']['auth_idp_url'])) {
Done

2019-05-31 13:56 UTC, ioigoume commented on app/View/OrgIdentities/fields.inc
> +                  print filter_var($org_identities[0]['OrgIdentity']['auth_idp_url'],FILTER_SANITIZE_SPECIAL_CHARS);
Done

2019-06-03 11:49 UTC, NicolasLiampotis requested changes

2019-06-03 11:49 UTC, NicolasLiampotis commented on app/Config/Schema/schema.xml
> +    <field name="authn_authority" type="C" size="128" />
Check if max size conforms to max length of SAML entityID

2019-06-03 11:49 UTC, NicolasLiampotis commented on app/Model/OrgIdentity.php
> +    $authIdPUrl = isset($_SERVER['AuthenticatingAuthority']) ? $_SERVER['AuthenticatingAuthority'] : null;
Rename authIdPUrl to authnAuthority

2019-06-03 11:49 UTC, NicolasLiampotis commented on app/Model/OrgIdentity.php
> +      $newOrgIdentity['OrgIdentity']['authn_authority'] = $authIdPUrl;
Rename authIdPUrl to authnAuthority

2019-06-03 12:39 UTC, ioigoume commented
Review fixes completed.

2019-06-04 10:26 UTC, NicolasLiampotis approved these changes

2019-06-04 10:26 UTC, NicolasLiampotis commented
LGTM!

2019-06-04 10:27 UTC, merged