Convert Petition comment to textarea
rciam/comanage-registry pull request #142
Opened 2021-10-29 10:25 UTC by lionick

`alter table cm_co_petition_attributes alter column value type varchar(4000) using value::varchar(4000);`

2021-10-29 13:22 UTC, ioigoume requested changes

2021-10-29 13:22 UTC, ioigoume commented on app/View/CoPetitions/petition-attributes.inc
>                  print $this->Form->input($fieldName, $args);
prefer to call `textarea` explicitly like this `$this->Form->textarea`

2021-10-29 13:22 UTC, ioigoume commented on app/View/CoPetitions/petition-attributes.inc
> +                  $string = $co_petition_attribute_values[ $ea['id'] ][ $ea['field'] ];
move string formatter to a method in `AppHelper`

2021-11-01 06:49 UTC, ioigoume approved these changes
LGTM

2021-11-01 10:12 UTC, NicolasLiampotis approved these changes
LGTM

2021-11-01 10:12 UTC, merged