api_user_co_access
rciam/comanage-registry pull request #156
Opened 2022-01-21 12:50 UTC by ioigoume

Api user co access

2022-01-28 08:08 UTC, lionick requested changes

2022-01-28 08:08 UTC, lionick commented on app/Controller/AppController.php
> +      if(!empty($_COOKIE['dev_co_registry_tz_auto'])) {
This should not be changed.

2022-01-28 08:08 UTC, lionick commented on app/Controller/AppController.php
> +        $this->set('vv_tz', $_COOKIE['dev_co_registry_tz_auto']);
This should not be changed.

2022-01-28 09:16 UTC, ioigoume commented on app/Controller/AppController.php
> +      if(!empty($_COOKIE['dev_co_registry_tz_auto'])) {
Done

2022-01-28 09:16 UTC, ioigoume commented on app/Controller/AppController.php
> +        $this->set('vv_tz', $_COOKIE['dev_co_registry_tz_auto']);
Done

2022-01-28 10:03 UTC, lionick approved these changes
LGTM

2022-02-01 09:15 UTC, NicolasLiampotis approved these changes
LGTM

2022-02-02 09:19 UTC, merged