API_introduce_cou_level_access
rciam/comanage-registry pull request #158
Opened 2022-02-03 12:08 UTC by ioigoume

Api User COU access control configuration view

2022-02-11 07:25 UTC, lionick requested changes

2022-02-11 07:25 UTC, lionick commented on app/View/CoPersonRoles/json/retrieve.ctp
> +    {
Fix the position of curly braces

2022-02-11 07:25 UTC, lionick commented on app/View/CoPersonRoles/json/retrieve.ctp
> +{
Fix the position of curly braces

2022-02-11 07:25 UTC, lionick commented on app/View/CoPersonRoles/json/retrieve.ctp
> +  {
Fix the position of curly braces

2022-02-11 07:25 UTC, lionick commented on app/Controller/ApiUsersController.php
> +      // and identifier types
do you mean add?

2022-02-11 07:29 UTC, ioigoume commented on app/View/CoPersonRoles/json/retrieve.ctp
> +{
Done

2022-02-11 07:30 UTC, ioigoume commented on app/View/CoPersonRoles/json/retrieve.ctp
> +  {
Done

2022-02-11 07:30 UTC, ioigoume commented on app/View/CoPersonRoles/json/retrieve.ctp
> +    {
Done

2022-02-11 07:35 UTC, ioigoume commented on app/Controller/ApiUsersController.php
> +      // and identifier types
Done

2022-02-14 07:49 UTC, lionick approved these changes
LGTM

2022-02-14 09:10 UTC, NicolasLiampotis approved these changes
LGTM

2022-02-14 09:10 UTC, merged