Implement notification on denial (CO-1658)
rciam/comanage-registry pull request #168
Opened 2022-03-17 08:28 UTC by lionick

DB CHANGES:
```alter table cm_co_enrollment_flows
	add denial_template_id int;

alter table cm_co_petitions
	add approver_comment varchar(256);

alter table cm_co_enrollment_flows
	add constraint cm_co_enrollment_flows_denial_template_id_fkey
		foreign key (denial_template_id) references cm_co_message_templates (id);```

2022-03-17 10:02 UTC, ioigoume requested changes

2022-03-17 10:02 UTC, ioigoume commented on app/Config/Schema/schema.xml
> +    <field name="approver_comment" type="C" size="256" />
let's make this type `text`

2022-03-17 10:02 UTC, ioigoume commented on app/Model/CoPetition.php
> +      'CoEnrollmentFlowFinMessageTemplate'
Do we need the comments?

2022-03-17 10:02 UTC, ioigoume commented on app/View/Elements/petitionActions.ctp
> +  print $this->Form->input('approver_comment',
Let's make this a textarea

2022-03-18 07:22 UTC, lionick commented on app/Config/Schema/schema.xml
> +    <field name="approver_comment" type="C" size="256" />
done

2022-03-18 07:23 UTC, lionick commented on app/Model/CoPetition.php
> +      'CoEnrollmentFlowFinMessageTemplate'
nope

2022-03-18 07:23 UTC, lionick commented on app/View/Elements/petitionActions.ctp
> +  print $this->Form->input('approver_comment',
done

2022-03-18 10:56 UTC, ioigoume approved these changes
LGTM

2022-03-21 13:07 UTC, merged