Set affiliation to empty if no value exists
rciam/comanage-registry pull request #177
Opened 2022-04-06 06:29 UTC by lionick

If mail is already verified, and IdP doesnt send voPersonEmailVerified then dont take this into account as change.

2022-04-12 10:32 UTC, ioigoume requested changes

2022-04-12 10:32 UTC, ioigoume commented on app/Model/Cert.php
> +      $failure_summary.= _txt('er.notfound', array(_txt('ct.org_identities.1'), $identifier));
Will this work if $failure_summary is null?

2022-04-12 10:41 UTC, lionick commented on app/Model/Cert.php
> +      $failure_summary.= _txt('er.notfound', array(_txt('ct.org_identities.1'), $identifier));
Done

2022-04-14 08:41 UTC, NicolasLiampotis approved these changes
LGTM

2022-04-14 08:41 UTC, merged