Added idp hinting in RCAUTH plugin. Fixed serious bug
rciam/comanage-registry pull request #18
Opened 2019-06-21 11:21 UTC by ioigoume

- Idp hinting for RCAuth plugin
- fixed serious bug

2019-06-26 08:30 UTC, ioigoume commented
I successfully tested the feature against rciam/rciam-3.1.x branch. After testing i made a few more changes like:
- better logging
- corrected parameter functions of inherited function
- added check for refresh token, since it is not always available

2019-06-27 08:00 UTC, NicolasLiampotis requested changes

2019-06-27 08:00 UTC, NicolasLiampotis commented on local/Plugin/RcauthSource/Lib/lang.php
> +	'pl.rcauthsource.issuer.desc'    => 'The issuer of the DN certificate',
The DN of the certificate issuer

2019-06-27 08:00 UTC, NicolasLiampotis commented on local/Plugin/RcauthSource/Model/RcauthSource.php
> +			'rule' => 'notBlank',
If the idp hint is supposed to be a URL change this to `'rule' => array('url', true),`

2019-06-27 08:04 UTC, ioigoume commented on local/Plugin/RcauthSource/Model/RcauthSource.php
> +			'rule' => 'notBlank',
Done

2019-06-27 08:05 UTC, ioigoume commented on local/Plugin/RcauthSource/Lib/lang.php
> +	'pl.rcauthsource.issuer.desc'    => 'The issuer of the DN certificate',
Done

2019-06-27 08:07 UTC, NicolasLiampotis approved these changes
LGTM

2019-06-27 08:08 UTC, merged