RCIAM-303_Show_whole_tree_for_cous_ui
rciam/comanage-registry pull request #64
Opened 2020-09-01 07:04 UTC by lionick

Show the whole tree of a cou, seperated by ":" (e.g parent:child:subchild) when adding person to a cou.

2020-09-01 09:39 UTC, ioigoume requested changes

2020-09-01 09:39 UTC, ioigoume commented on app/Model/Cou.php
> +   * @since  COmanage Registry v3.1
v3.1.1 instead of 3.1

2020-09-01 09:39 UTC, ioigoume commented on app/Model/Cou.php
> +    if(empty($parent)) {
Why not even shorter?
$parent = empty($parent) ? $this->getParentCouById($parentCouId) : $parent;

2020-09-01 09:39 UTC, ioigoume commented on app/Model/Cou.php
> +      $parent_id = $parent['Cou']['parent_id'];
$parent_id is redundant

2020-09-07 09:53 UTC, NicolasLiampotis approved these changes
LGTM

2020-09-07 09:53 UTC, merged