Show the last updated aups to the user at aups panel
rciam/comanage-registry pull request #82
Opened 2020-12-11 07:52 UTC by lionick

2020-12-11 08:50 UTC, lionick commented
Is related with https://github.com/rciam/comanage-registry/pull/78

2020-12-17 14:02 UTC, ioigoume requested changes

2020-12-17 14:02 UTC, ioigoume commented on app/View/CoTermsAndConditions/review.ctp
> +               ,
indentation of array

2020-12-17 14:03 UTC, lionick commented on app/View/CoTermsAndConditions/review.ctp
> +               ,
done

2020-12-17 14:05 UTC, ioigoume commented
LGTM

2021-01-13 09:25 UTC, NicolasLiampotis approved these changes
LGTM

2021-01-13 09:27 UTC, merged