Bulk_email_shell
rciam/comanage-registry pull request #93
Opened 2021-03-31 13:09 UTC by ioigoume

JobShell that constructs and sends bulk emails

Command Structure
```bash
app/Console/cake BulkEmail <action> <CO Name> <Email Subject> <Email Body>
```

Example
```bash
app/Console/cake BulkEmail igtf_update "RCIAM User Community" "My subject text" "Follow the instruction <a href='#'>here</a>"
```

2021-03-31 13:25 UTC, lionick requested changes

2021-03-31 13:25 UTC, lionick commented on app/Console/Command/BulkEmailShell.php
> +            $this->sendEmail(
maybe put sendEmail inside "if(!empty($results))" in order to be more straightforward

2021-03-31 16:08 UTC, ioigoume commented on app/Console/Command/BulkEmailShell.php
> +            $this->sendEmail(
Done

2021-04-01 14:27 UTC, NicolasLiampotis approved these changes
LGTM

2021-04-01 14:27 UTC, merged